<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="es">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Ejemplo: datos electorales • territorial</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png">
<link rel="icon" type="”image/svg+xml”" href="../favicon.svg">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<link rel="icon" sizes="any" href="../favicon.ico">
<link rel="manifest" href="../site.webmanifest">
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.8/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.8/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="ejemplo_servel_files/libs/quarto-html/popper.min.js"></script><script src="ejemplo_servel_files/libs/quarto-html/tippy.umd.min.js"></script><link href="ejemplo_servel_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ejemplo_servel_files/libs/quarto-html/light-border.css" rel="stylesheet">
<!-- pkgdown --><script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<meta property="og:title" content="Ejemplo: datos electorales">
<meta property="og:image" content="https://bastianolea.github.io/territorial/logo.png">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Ir al contenido</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Navegación del sitio"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">territorial</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.9.2</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Cambiar la navegación">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../articles/territorial.html">Primeros pasos</a></li>
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Índice</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-art-culos" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Artículos</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-art-culos">
<li><a class="dropdown-item" href="../articles/localidades.html">Localidades</a></li>
    <li><a class="dropdown-item" href="../articles/codigos_unicos_territoriales.html">Códigos Únicos Territoriales</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Tutoriales</h6></li>
    <li><a class="dropdown-item" href="../articles/mapas_comunales.html">Mapas comunales</a></li>
    <li><a class="dropdown-item" href="../articles/mapas_regionales_macrozonas.html">Mapas regionales por macrozona</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Ejemplos</h6></li>
    <li><a class="dropdown-item" href="../articles/suciedad_extrema.html">Prueba de suciedad extrema</a></li>
    <li><a class="dropdown-item" href="../articles/ejemplo_servel.html">Ejemplo: datos electorales</a></li>
    <li><a class="dropdown-item" href="../articles/ejemplo_bibliotecas.html">Ejemplo: préstamos en bibliotecas</a></li>
    <li><a class="dropdown-item" href="../articles/ejemplo_sercotec.html">Ejemplo: beneficiarios Sercotec</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Registro de cambios</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Buscar en el sitio" placeholder="Buscar" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/bastianolea/territorial/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Ejemplo: datos electorales</h1>




      <small class="dont-index">Código: <a href="https://github.com/bastianolea/territorial/blob/main/vignettes/articles/ejemplo_servel.qmd" class="external-link"><code>vignettes/articles/ejemplo_servel.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <p>En este ejemplo usaremos el paquete de R <a href="https://bastianolea.github.io/territorial">territorial</a> para llevar a cabo una limpieza de datos territoriales correspondientes a afiliaciones a partidos políticos por sexo y edad. Los datos fueron obtenidos por una solicitud de transparencia (Concejo por la Transparencia) al Servicio Electoral (Servel) de Chile en el año 2025.</p>
<p>Estos datos son públicos y oficiales, y fueron obtenidos como parte del desarrollo del <a href="https://www.descentralizachile.cl/ibg/" class="external-link">Índice de Brechas de Género</a> de Subdere.</p>
<p>Puedes <a href="https://github.com/bastianolea/territorial/raw/main/data-raw/ejemplo_servel_partidos.xlsx" class="external-link">descargar aquí los datos</a> para seguir el ejemplo.</p>
<hr>
<p>Primero cargamos los datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org" class="external-link">readxl</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://here.r-lib.org/" class="external-link">here</a></span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /home/runner/work/territorial/territorial</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">servel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html" class="external-link">read_xlsx</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://here.r-lib.org/reference/here.html" class="external-link">here</a></span><span class="op">(</span><span class="st">"data-raw/ejemplo_servel_partidos.xlsx"</span><span class="op">)</span>,</span>
<span>  skip <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span><span class="va">servel</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12,091 × 19
   `,`        REGION COMUNA SEXO  `0-19` `20-24` `25-29` `30-34` `35-39` `40-44`
   &lt;chr&gt;      &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 RENOVACIO… DE AN… ANTOF… M          0      10      17      39      36      45
 2 RENOVACIO… DE AN… ANTOF… V          1       5      19      31      43      39
 3 RENOVACIO… DE AN… CALAMA M          0       2      12      13      11      11
 4 RENOVACIO… DE AN… CALAMA V          0       0      16      13      11      16
 5 RENOVACIO… DE AN… MARIA… M          0       2       0       3       1       2
 6 RENOVACIO… DE AN… MARIA… V          0       1       2       1       0       0
 7 RENOVACIO… DE AN… MEJIL… M          0       0       0       0       0       0
 8 RENOVACIO… DE AN… MEJIL… V          0       0       1       0       2       1
 9 RENOVACIO… DE AN… OLLAG… M          0       0       1       0       0       0
10 RENOVACIO… DE AN… OLLAG… V          0       1       0       0       0       0
# ℹ 12,081 more rows
# ℹ 9 more variables: `45-49` &lt;dbl&gt;, `50-54` &lt;dbl&gt;, `55-59` &lt;dbl&gt;,
#   `60-64` &lt;dbl&gt;, `65-69` &lt;dbl&gt;, `70-74` &lt;dbl&gt;, `75-79` &lt;dbl&gt;, `80+` &lt;dbl&gt;,
#   TOTAL &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Realizamos una transformación de los datos para que pasen a desde columnas hacia filas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org" class="external-link">tidyr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">servel</span> <span class="op">&lt;-</span> <span class="va">servel</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html" class="external-link">pivot_longer</a></span><span class="op">(</span></span>
<span>    cols <span class="op">=</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/where.html" class="external-link">where</a></span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span>,</span>
<span>    names_to <span class="op">=</span> <span class="st">"edad"</span>, </span>
<span>    values_to <span class="op">=</span> <span class="st">"afiliados"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">servel</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 181,365 × 6
   `,`                 REGION         COMUNA      SEXO  edad  afiliados
   &lt;chr&gt;               &lt;chr&gt;          &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;
 1 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     0-19          0
 2 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     20-24        10
 3 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     25-29        17
 4 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     30-34        39
 5 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     35-39        36
 6 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     40-44        45
 7 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     45-49        39
 8 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     50-54        37
 9 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     55-59        43
10 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     60-64        22
# ℹ 181,355 more rows</code></pre>
</div>
</div>
<p>Ahora realizamos una limpieza de los nombres de las columnas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org" class="external-link">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/sfirke/janitor" class="external-link">janitor</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">servel</span> <span class="op">&lt;-</span> <span class="va">servel</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html" class="external-link">clean_names</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html" class="external-link">rename</a></span><span class="op">(</span>partido <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span><span class="va">servel</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 181,365 × 6
   partido             region         comuna      sexo  edad  afiliados
   &lt;chr&gt;               &lt;chr&gt;          &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;
 1 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     0-19          0
 2 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     20-24        10
 3 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     25-29        17
 4 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     30-34        39
 5 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     35-39        36
 6 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     40-44        45
 7 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     45-49        39
 8 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     50-54        37
 9 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     55-59        43
10 RENOVACION NACIONAL DE ANTOFAGASTA ANTOFAGASTA M     60-64        22
# ℹ 181,355 more rows</code></pre>
</div>
</div>
<p>Finalmente, para siplificar el ejemplo, sumamos la cantidad de afiliados/as a partidos políticos por región, comuna y sexo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">servel</span> <span class="op">&lt;-</span> <span class="va">servel</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html" class="external-link">summarize</a></span><span class="op">(</span></span>
<span>    afiliados <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">afiliados</span><span class="op">)</span>,</span>
<span>    .by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">region</span>, <span class="va">comuna</span>, <span class="va">partido</span>, <span class="va">sexo</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code></pre></div>
</div>
<p>Ahora cargamos el paquete <a href="https://bastianolea.github.io/territorial">territorial</a>, y la primera acción será validar las comunas presentes en los datos, para percatarnos de cualquier problema:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://bastianolea.github.io/territorial">territorial</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">servel</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="../reference/validar_comunas.html">validar_comunas</a></span><span class="op">(</span><span class="va">comuna</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>! Resumen: 12091 casos de comunas que no conciden con comunas correctamente escritas (ver `territorial::comunas()`): ANTOFAGASTA, CALAMA, MARIA ELENA, MEJILLONES, OLLAGUE, SAN PEDRO DE ATACAMA, SIERRA GORDA, TALTAL, TOCOPILLA, ARICA y 337 comunas más</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>! Mayúsculas: 12091 casos de comunas escritas en mayúsculas: ANTOFAGASTA, CALAMA, MARIA ELENA, MEJILLONES, OLLAGUE, SAN PEDRO DE ATACAMA, SIERRA GORDA, TALTAL, TOCOPILLA, ARICA y 337 comunas más</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Tildes: 2373 casos de comunas que deberían tener tildes y no los tienen: MARIA ELENA, COPIAPO, AYSEN, RIO IBAÑEZ, COMBARBALA, RIO HURTADO, CURACAUTIN, PITRUFQUEN, PUCON, PUREN y 61 comunas más</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Eñes: 29 casos de comunas que deberían tener diéresis (¨) y no tienen: OLLAGUE</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Escrituras alternativas: 31 casos de comunas escritas de una forma no recomendada, aunque válida: PAIGUANO</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✖ Validación de comunas: se encontraron 26615 problemas con las comunas! Usa `territorial::limpiar_comunas()` para solucionarlos.</code></pre>
</div>
</div>
<p>Vemos que hay miles de comunas escritas en mayúsculas, más de 2 mil comunas sin tildes, 29 casos de comunas sin eñes, y formas incorrectas de escribir comunas.</p>
<p>Para arreglar las comunas mal escritas, usaremos la función <code><a href="../reference/limpiar_comunas.html">limpiar_comunas()</a></code> sobre la columna original, para crear una columna de nombres limpios:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">servel_limpio</span> <span class="op">&lt;-</span> <span class="va">servel</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span>nombre_comuna <span class="op">=</span> <span class="fu"><a href="../reference/limpiar_comunas.html">limpiar_comunas</a></span><span class="op">(</span><span class="va">comuna</span>, procedimiento <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Limpiando 12091 nombres de comunas (347 son distintas)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>→ Paso 1: confirmar comunas correctas</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ De las 347 comunas distintas, ninguna tiene nombres 100% correctos. Los siguientes pasos intentarán la limpieza...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>→ Paso 2: coincidencias por limpieza de texto</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ A partir de la limpieza de texto, se limpiaron 343 de 347 comunas: Antofagasta, Calama, María Elena, Mejillones, Ollagüe, San Pedro de Atacama, Sierra Gorda, Taltal, Tocopilla, Arica y 333 comunas más</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>→ Paso 3: casos especiales</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Se encontró 1 caso especial: Cabo de Hornos</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>→ Paso 4: coincidencias aproximadas de texto</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>! Se encontraron 2 coincidencias para la comuna "marchigue": la higuera y marchihue</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>! No se encontró ninguna coincidencia para la comuna "fuera del pais"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Se limpiaron 2 de 3 comunas por medio de coincidencias aproximadas de texto: Paihuano y Marchihue</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>→ Conclusión de limpieza de comunas</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ De las 347 comunas distintas, se limpiaron 346 en total (99.7%)</code></pre>
</div>
</div>
<p>La función nos informa que, de las 347 comunas distintas presentes en la tabla de datos, se limpiaron 346 en total (99.7%).</p>
<p>Algunos casos que vemos en el registro son:</p>
<ul>
<li>Paihuano y Marchihue fueron limpiadas a pesar de estar escritas distinto</li>
<li>Cabo de Hornos fue limpiada por tratarse de un caso especial, que generalmente viene muy mal escrito (le ponen “Ex-Navarino” o similares al final, dificultando limpieza automatizada</li>
<li>La comuna “Fuera del país” no fue convertida, por la obviedad de no tratarse de una comuna</li>
</ul>
<p>Ahora vemos cómo quedaron los datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">servel_limpio</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12,091 × 6
   region         comuna      partido             sexo  afiliados nombre_comuna
   &lt;chr&gt;          &lt;chr&gt;       &lt;chr&gt;               &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;
 1 DE ANTOFAGASTA ANTOFAGASTA RENOVACION NACIONAL M           748 Antofagasta
 2 DE ANTOFAGASTA ANTOFAGASTA RENOVACION NACIONAL V           676 Antofagasta
 3 DE ANTOFAGASTA CALAMA      RENOVACION NACIONAL M           294 Calama
 4 DE ANTOFAGASTA CALAMA      RENOVACION NACIONAL V           288 Calama
 5 DE ANTOFAGASTA MARIA ELENA RENOVACION NACIONAL M            38 María Elena
 6 DE ANTOFAGASTA MARIA ELENA RENOVACION NACIONAL V            24 María Elena
 7 DE ANTOFAGASTA MEJILLONES  RENOVACION NACIONAL M            10 Mejillones
 8 DE ANTOFAGASTA MEJILLONES  RENOVACION NACIONAL V            20 Mejillones
 9 DE ANTOFAGASTA OLLAGUE     RENOVACION NACIONAL M             8 Ollagüe
10 DE ANTOFAGASTA OLLAGUE     RENOVACION NACIONAL V            12 Ollagüe
# ℹ 12,081 more rows</code></pre>
</div>
</div>
<p>Queda limpiar las regiones. Primero las validamos con <code><a href="../reference/validar_regiones.html">validar_regiones()</a></code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">servel_limpio</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="../reference/validar_regiones.html">validar_regiones</a></span><span class="op">(</span><span class="va">region</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>! Mayúsculas: 12091 casos de regiones escritas en mayúsculas</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>! Ortografía: 3205 casos de regiones escritas sin tilde</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✖ Validación de regiones: se encontraron 15296 problemas con las regiones!</code></pre>
</div>
</div>
<p>Nuevamente encontramos un caos de nombres de regiones. Pero, como ya obtuvimos las comunas limpias, podemos usar la función <code><a href="../reference/contextualizar.html">contextualizar()</a></code> para basarnos en las comunas limpias para agregar columnas que contextualicen dichas comunas en sus respectivas provincias y regiones:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">servel_limpio</span> <span class="op">&lt;-</span> <span class="va">servel_limpio</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="../reference/contextualizar.html">contextualizar</a></span><span class="op">(</span><span class="va">nombre_comuna</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="co"># agregar columnas territoriales nuevas</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html" class="external-link">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">region</span>, <span class="op">-</span><span class="va">comuna</span><span class="op">)</span> <span class="co"># remover columnas originales</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>! 46 filas no coincidieron con `territorial::territorios` y quedarán con NA</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Columnas agregadas: codigo_region, nombre_region, codigo_provincia, nombre_provincia y codigo_comuna</code></pre>
</div>
</div>
<p>Repetimos la validación para confirmar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">servel_limpio</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="../reference/validar_regiones.html">validar_regiones</a></span><span class="op">(</span><span class="va">nombre_region</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ Todas las regiones están correctas!</code></pre>
</div>
</div>
<p>Terminamos con datos territoriales limpios!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">servel_limpio</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12,091 × 9
   codigo_region nombre_region codigo_provincia nombre_provincia codigo_comuna
           &lt;dbl&gt; &lt;chr&gt;                    &lt;dbl&gt; &lt;chr&gt;                    &lt;dbl&gt;
 1             2 Antofagasta                 21 Antofagasta               2101
 2             2 Antofagasta                 21 Antofagasta               2101
 3             2 Antofagasta                 22 El Loa                    2201
 4             2 Antofagasta                 22 El Loa                    2201
 5             2 Antofagasta                 23 Tocopilla                 2302
 6             2 Antofagasta                 23 Tocopilla                 2302
 7             2 Antofagasta                 21 Antofagasta               2102
 8             2 Antofagasta                 21 Antofagasta               2102
 9             2 Antofagasta                 22 El Loa                    2202
10             2 Antofagasta                 22 El Loa                    2202
# ℹ 12,081 more rows
# ℹ 4 more variables: nombre_comuna &lt;chr&gt;, partido &lt;chr&gt;, sexo &lt;chr&gt;,
#   afiliados &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html" class="external-link">glimpse</a></span><span class="op">(</span><span class="va">servel_limpio</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 12,091
Columns: 9
$ codigo_region    &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,…
$ nombre_region    &lt;chr&gt; "Antofagasta", "Antofagasta", "Antofagasta", "Antofag…
$ codigo_provincia &lt;dbl&gt; 21, 21, 22, 22, 23, 23, 21, 21, 22, 22, 22, 22, 21, 2…
$ nombre_provincia &lt;chr&gt; "Antofagasta", "Antofagasta", "El Loa", "El Loa", "To…
$ codigo_comuna    &lt;dbl&gt; 2101, 2101, 2201, 2201, 2302, 2302, 2102, 2102, 2202,…
$ nombre_comuna    &lt;chr&gt; "Antofagasta", "Antofagasta", "Calama", "Calama", "Ma…
$ partido          &lt;chr&gt; "RENOVACION NACIONAL", "RENOVACION NACIONAL", "RENOVA…
$ sexo             &lt;chr&gt; "M", "V", "M", "V", "M", "V", "M", "V", "M", "V", "M"…
$ afiliados        &lt;dbl&gt; 748, 676, 294, 288, 38, 24, 10, 20, 8, 12, 8, 6, 14, …</code></pre>
</div>
</div>



<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Desarrollado por <a href="https://bastianolea.rbind.io" class="external-link">Bastián Olea Herrera</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Sitio creado con <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.1.</p>
</div>

    </footer>
</div>





  </body>
</html>
